### ISSUE TITLE
Annunciare il raduno

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#1]
Entro venerdì prossimo è da annunciare.

@gpirrotta vuoi in contemporanea preparare un blog post su OpenARS?
Così si annuncia raduno e si introduce OpenARS

Ecco una pagina bianca dove scrivere il testo di lancio https://docs.google.com/document/d/1MzOpbq8jEiPqLo0B-TE5--J7EtJNrwS7qyK8yj7lv5Y/edit?usp=sharing

- [x] testo presentazione OpenARS
- [x] testo presentazione raduno

**Comment by gpirrotta** [comment]
Ok, il blog post di annuncio di OpenARS all'interno del raduno lo scrivo e lo carico su opendatasicilia

**Comment by aborruso** [comment]
Ecco il testo di presentazione di OpenARS https://docs.google.com/document/d/1MzOpbq8jEiPqLo0B-TE5--J7EtJNrwS7qyK8yj7lv5Y/edit#heading=h.8aog8kt9adun

**Comment by nelsonmau** [comment]
non ho capisco se manca qualcosa o se va bene così (io cmq eviterei di fare troppi testi, ne basta uno imho)

**Comment by aborruso** [comment]
Ok io direi che ci siamo.

Domani dalle 8:30 in poi lanciamo tutto. 

@gpirrotta pubblica alla stessa ora sul blog di ODS il post che ha in bozza (in cui inserire il link al sito ufficiale del raduno). Ok?

**Comment by gpirrotta** [comment]
@aborruso ho inserito il link al sito ufficiale e ho pianificato la pubblicazione per domani alle 8.30
