### ISSUE TITLE
Assegniamoci dei ruoli per le varie "cose da fare"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#11]
Vorrei che ci fossero i

- [x] "responsabili sito" (io, @gbvitrano e @nelsonmau)
- [x] "responsabili eventbrite" (@picomiles )
- [x] "responsabili hackathon"
- [x] "responsabili contenuti e programma convegno (@gpirrotta e @dtaibi)"
- [ ] "responsabili ..."

Altrimenti è troppo lasciato alla spontaneità e rischiamo di scivolare sulla buccia di banana

**Comment by nelsonmau** [comment]
responsabili contenuti visto il tema direi che non possono non essere @gpirrotta e @dtaibi

per il resto io posso seguire il sito e occuparmi di un tavolo dell'hackathon insieme a uno tra i due sopra citati :-)

**Comment by aborruso** [comment]
Metto allora @picomiles su eventbrite

**Comment by dtaibi** [comment]
Per me ok! Ovviamente se si vuole aggiungere qualcun altro fate un fischio

  Davide

**Comment by gpirrotta** [comment]
@aborruso ok. Per il programma dell'evento io farei un google form dove far sottomettere gli interventi. Per l'organizzazione dell'hackathon possiamo stilare un elenco di possibili "outcome" da portare a casa e su quelli creare i tavoli di lavoro. Posso occuparmene però da lunedì. Oggi e domani sono con l'acqua alla gola.

**Comment by gbvitrano** [comment]
per me ok
