### ISSUE TITLE
compriamo gli adesivi esagonali? 

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/Palermo2018#13]
all'epoca fece @aborruso (ma non ricordo il costo).

possiamo chiedere a Ondata di anticipare il costo, direi circa 150/200 euri se non erro

**Comment by aborruso** [comment]
Sul mitico stickermule. Ai tempi 100 li pagammo 58€.
Si paga il taglio esagonale, che secondo me è una figata.

Io li stamperei
