### ISSUE TITLE
Definire "regole" e modalità per ricevere proposte di intervento

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#14]
Ho momentaneamente [modificato](https://github.com/opendatasicilia/Palermo2018/commit/de06ace2c6b6951fff7c9eae209c7498ebb5cab8) "interamente" dedicato a LOD con "principalmente". Lo segnalo principalmente a @gpirrotta e @dtaibi che sono "responsabili contenuti e programma convegno" :)

Io sarei per non stringere ai soli LOD, ma segnalare soltanto una preferenza.

Sul sito al momento è stato predisposto un invio di proposta di intervento per email. Tocca definire:

- se vogliamo usare l'email, o una issue qui usando un template di issue (secondo me sarebbe fico e aperto e creerebbe emulazione), o altro modo;
- se c'è da allegare un abstract e se sì come deve essere fatto;
- dare visibilità ai "responsabili contenuti e programma convegno" sul sito.

**Comment by gpirrotta** [comment]
Ho creato questo Google Form:
https://goo.gl/forms/tNnJTf7oOGbiGhCF3
inserendo anche @dtaibi tra i collaboratori. 

2981718644d55e40483325ce6d630bca27fba289

**Comment by gpirrotta** [comment]
All'interno del Google Form ho inserito anche la seguente **call for contribution**:

L' edizione di quest'anno del raduno è dedicata principalmente ai Linked Open Data. Puoi proporre un intervento su seguenti temi:
- utilizzo di Linked Data nel mondo della Pubblica Amministrazione, nelle aziende italiane, nel terzo settore;
- data-journalism e visualizzazioni basate sui Linked Data;
- iniziative, progetti, best-practices su Open Government, Trasparenza, Opendata.

Invia la tua candidatura e ti daremo un feedback entro il 15 ottobre.
