### ISSUE TITLE
predisporre communication kit (sorf of)

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#16]
Ci sarebbe da predisporre:

- [x] immagine per cover gruppo facebook ODS (penso ci sia già, @nelsonmau confermi);
- [ ] immagine per cover facebook, simile alla prima, ma con un ribbon, una striscia (vedi esempio 2016). Questa si potrebbe inviare a chi si iscrive su eventbrite;

![image](https://user-images.githubusercontent.com/30607/45597984-c25ed400-b9d4-11e8-8269-59eb697c0f94.png)

- [ ] predisporre cover per twitter di ODS;
- [ ] predisporre ribbon per chi vuole metterlo nei propri siti (vedi esempio);

![image](https://user-images.githubusercontent.com/30607/45597990-defb0c00-b9d4-11e8-9b1c-0b8a6aa9fe06.png)

Nella bella **pagina del 2016**, molti spunti: https://github.com/SiciliaHub/ods16/tree/gh-pages/comunicazione#c%C3%A8-ods16-dillo-a-tutti

@nelsonmau riesci a creare la versione SVG della grafica che hai predisposto, mettendo a disposizione eventuali speciali font usati?

**Comment by cirospat** [comment]
ForumPA (media partner del raduno), nella persona di Giovanna Stagno, mi ha chiesto la disponibilità di un paper da usare per la comunicazione sul loro sito forumpa.it e nei social.
Un paper con:
- loghi di ODS e dei partner
- titolo evento
- data evento
- luogo evento

**Comment by aborruso** [comment]
Aggiungo delle specifiche arrivate dopo il messaggio di @cirospat 

- [ ] un banner formato 300X100 (statico oppure animato), che pubblicheremo sul nostro sito forumpa.it con link all'evento
- [ ] una social card dell'evento che faremo girare sui nostri canali
- [ ] un articolo di presentazione dell'evento
