### ISSUE TITLE
Definizione tavoli di lavoro hackathon

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/Palermo2018#17]
Per l'organizzazione dell'hackathon di giorno 10 ho inserito qualche idea su questo foglio:

https://docs.google.com/spreadsheets/d/1dKiPMXH66uehRSvTawIHNGlU-pVyXM-YPsIS0rqHp3M/edit?usp=sharing

Se avete in mente qualche idea che vi piacerebbe sviluppare quel giorno aggiungete alla fine.

**Comment by nelsonmau** [comment]
ciao caros, magari non è proprio un track ma ho proposto questo

titolo | descr | output
-- | -- | --
Popolare la voce di wikipedia https://it.wikipedia.org/wiki/Linked_data | voce wiki popolata | saperne un po' e avere un po' di fonti da citare

**Comment by giuragu** [comment]
Ciao @gpirrotta,
siccome non sono proprio in carreggiata e potrei essermi perso qualcosa. Il tema Amministrazione Trasparente ARS sarebbe da inserire qui eventualmente giusto? E comunque sempre che si trovi un qualcosa che lo faccia diventare un tema "linked". Corretto?

**Comment by aborruso** [comment]
In attesa della risposta di @gpirrotta : questo è lo spazio per proporre temi, sopratutto quelli ancora non inseriti :)

In modo da andare poi a sintesi. Quindi sta a te proporre l'hackathon a tema. Non c'è l'obbligo credo a essere linked, basta non andare troppo fuori tema. Insomma proponi e i professori @gpirrotta e @dtaibi lo valuteranno :)

**Comment by gpirrotta** [comment]
@nelsonmau 
per popolare la pagina intendi allinearla alla versione inglese?

> ciao caros, magari non è proprio un track ma ho proposto questo
> 
> titolo	descr	output
> Popolare la voce di wikipedia https://it.wikipedia.org/wiki/Linked_data	voce wiki popolata	saperne un po' e avere un po' di fonti da citare
