### ISSUE TITLE
Hangout organizzativo

### ISSUE THREAD

**Issue by dtaibi** [opendatasicilia/Palermo2018#18]
Vi ricordo l'hangout di domani 19 settembre alle 19. 

Di seguito il link per partecipare: 

https://hangouts.google.com/hangouts/_/calendar/ZGF2aWRlLnRhaWJpQGdtYWlsLmNvbQ.48if3ncoc4m94hsioo2von2gu2?authuser=0

**Comment by aborruso** [comment]
alcuni spunti:

- valutazione presenza ordine dei giornalisti;
- organizzare webinar di presentazione;
- pubblicare post didattici da qui al raduno;
- raccogliere bibliografia di riferimento;
