### ISSUE TITLE
preparare immagine cover per facebook e twitter

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#2]

**Comment by nelsonmau** [comment]
sono tutti screenshot


https://github.com/opendatasicilia/Palermo2018/blob/master/img/ods18-fotoTimeline.png

https://github.com/opendatasicilia/Palermo2018/blob/master/img/ods18-coverFB.png

https://github.com/opendatasicilia/Palermo2018/blob/master/img/ods18-raw.png

**Comment by peppelamensa** [comment]
Proverei solo a cambiare il nero su bianco del "Linked", oppure il carattere: mi pare richiami troppo LinkedIn

**Comment by dtaibi** [comment]
non si può avere un cielo più siciliano? :-)
Troppo grigio non ci sono abituato!

**Comment by cirospat** [comment]
ah ah Davide
bellissima osservazione e giustissima!!!
ma considera che quella foto  l'ha selezionata uno che vive a Milano
:P :P :P


_
*Ciro Spataro*
cirospat@gmail.com
cirospat.readthedocs.io




2018-09-11 13:18 GMT+02:00 dtaibi <notifications@github.com>:

**Comment by nelsonmau** [comment]
sucate! :D 

ho messo questa https://upload.wikimedia.org/wikipedia/commons/a/af/Palazzo_Normanni%2C_vista%2C_Palermo.jpg

e sistemato il resto che segnalate, check please (ctrl+f5 se non vi si aggiorna)

**Comment by nelsonmau** [comment]
vanno bene queste nuove immagini?
soprattutto @dtaibi e @cirospat che mi perculeggiavano un po' ^_^

https://github.com/opendatasicilia/Palermo2018/blob/master/img/ods18-raw.png

https://github.com/opendatasicilia/Palermo2018/blob/master/img/ods18-fotoTimeline.png

**Comment by cirospat** [comment]
Qualche timida nuvoletta la possiamo tollerare, no Davide?
:P

Il gio 13 set 2018, 15:59 Andrea Nelson Mauro <notifications@github.com> ha
scritto:

**Comment by dtaibi** [comment]
Timida si! ;-)

  Davide

**Comment by nelsonmau** [comment]
addocu carusi, lo prendo come un "visto si stampi!"
