### ISSUE TITLE
organizzazione light lunch del sabato 10 nov ai Cantieri della Zisa

### ISSUE THREAD

**Issue by UO-TransizioneDigitaleComunePalermo** [opendatasicilia/Palermo2018#20]
c'è un servizio di bar all'interno dei cantieri culturali della zisa che possa soddisfare la fame di tane persone oppure bisogna organizzare qualcosa: catering?

**Comment by aborruso** [comment]
Yes @UO-TransizioneDigitaleComunePalermo nel coworking c'è un bello spazio cucina e ci appoggeremo lì.

Conto su di te e altri palermitani per andare a fare un sopralluogo.

**Comment by cirospat** [comment]
ok bene

**Comment by marcofromsicily** [comment]
C'è Cantiere Cucina 

https://www.facebook.com/groups/cantierecucina
