### ISSUE TITLE
Facciamo dei segnalibri?

### ISSUE THREAD

**Issue by giuragu** [opendatasicilia/Palermo2018#21]
Raccogliendo la proposta di Salvatore Fiandaca mi accingerò a chiedere dei preventivi.
Intanto il grande @gbvitrano ha realizzato una bozza
![prima bozza](https://user-images.githubusercontent.com/12112056/45811090-79f13000-bccc-11e8-94b9-b387d5a09e30.jpg)

**Comment by gbvitrano** [comment]
Troppo buono, è solo il print screen in modalità mobile :-)

**Comment by giuragu** [comment]
Ciao,
con clamoroso ritardo torno e vi dico che possiamo avere circa 200 segnalibri entro giovedì (solo fronte) per €20 (100 segnalibri verrebbero €15 quindi andrei per i 200). Li porterei io. Servono proposte di "immagine"

**Comment by giuragu** [comment]
Ah dimenticavo...entro giovedì se li ordino entro domani mattina...

**Comment by giuragu** [comment]
Grazie al contributo fondamentale di @gbvitrano i segnalibri sono in stampa e pronti per giovedì
