### ISSUE TITLE
Loghi partners

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/Palermo2018#22]
ho iniziato a metterli online

ce ne sono altri?

![2018 09 20-ods2018 opendatasicilia it- screenshot](https://user-images.githubusercontent.com/1769578/45817915-7667a400-bce0-11e8-813c-182bb4b3c765.png)

**Comment by peppelamensa** [comment]
![logo-leva-arancio-piccolo](https://user-images.githubusercontent.com/10743708/45824097-7a4ef280-bcef-11e8-9906-eaa4a3dda3c1.jpg)
![logo-leva-arancio-bianco-piccolo](https://user-images.githubusercontent.com/10743708/45824111-833fc400-bcef-11e8-9c1a-a735c81abcba.jpg)

**Comment by peppelamensa** [comment]
uno dei due

**Comment by gbvitrano** [comment]
Nella pagina manca il logo di ODS, è una scelta?

**Comment by gbvitrano** [comment]
@peppelamensa ho sostituito immagine di leva digitale ho messo 
![leva_red_01](https://user-images.githubusercontent.com/20488693/45831114-d40ae900-bcfe-11e8-8ec8-544c194c9925.jpg)

**Comment by gbvitrano** [comment]
I loghi di ARS, Regione Siciliana e cre.zi.plus non vanno messi?

**Comment by cirospat** [comment]
logo FPA (media partner)
![image](https://user-images.githubusercontent.com/3757525/46205253-3d52b380-c320-11e8-953f-188877a645a4.png)

http://www.forumpa.it/assets/site/brand-forum-pa.jpg
