### ISSUE TITLE
mancanza di Event (schema.org) in json-ld

### ISSUE THREAD

**Issue by senzanome75** [opendatasicilia/Palermo2018#24]
Salve,

Penso che potrebbe dare una mano includere (almeno) l'Event in json-ld al sito...

Qui 2 link per generarlo...

- [Schema Markup Generator (JSON-LD)](https://technicalseo.com/seo-tools/schema-markup-generator/)

- [Assistenza per il markup](https://www.google.com/webmasters/markup-helper/u/0/)

Poi andrebbe validato qui... [Strumento di test per i dati strutturati](https://search.google.com/structured-data/testing-tool)

Ormai il tempo è veramente poco ma credo che si potrebbero ottimizzare altre cose.

**Comment by aborruso** [comment]
ciao @senzanome75 se generi il codice e lo incolli qui (o con una un pull request su git) ti seguiamo rapidamente.

Grazie

**Comment by senzanome75** [comment]
Questo è per giorno 9

`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "(Linked) OpenData Sicilia (Conferenza all'ARS)",
  "description": "La comunità OpenDataSicilia si ritrova il 9 e il 10 novembre 2018 a Palermo per il proprio raduno dedicato al tema degli OpenData e aperto a chiunque voglia partecipare.",
  "image": "http://ods2018.opendatasicilia.it/img/ods18-fotoTimeline.png",
  "startDate": "2018-11-09T09:00",
  "endDate": "2018-11-09T19:00",
  "performer": {
    "@type": "PerformingGroup",
    "name": "OpenData Sicilia"
  },
  "location": {
    "@type": "Place",
    "name": "Palazzo Reale",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Paizza del Parlamento, 1",
      "addressLocality": "Palermo",
      "postalCode": "90129",
      "addressCountry": "IT"
    }
  }
}
</script>`

Questo è per giorno 10
`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "(Linked) OpenData Sicilia (Hackaton)",
  "description": "La comunità OpenDataSicilia si ritrova il 9 e il 10 novembre 2018 a Palermo per il proprio raduno dedicato al tema degli OpenData e aperto a chiunque voglia partecipare.",
  "image": "http://ods2018.opendatasicilia.it/img/ods18-fotoTimeline.png",
  "startDate": "2018-11-10T09:00",
  "endDate": "2018-11-10T19:00",
  "performer": {
    "@type": "PerformingGroup",
    "name": "OpenData Sicilia"
  },
  "location": {
    "@type": "Place",
    "name": "Crezi Plus, Cantieri Culturali alla Zisa",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "via Paolo Gili, 4",
      "addressLocality": "Palermo",
      "postalCode": "90134",
      "addressCountry": "IT"
    }
  }
}
</script>`

Andrebbero messi nell'head della pagina... forse si potrebbero raffinare le description oppure fare un unico event (ma in quel caso non si potrebbero localizzare)...

L'ho generato con https://technicalseo.com/seo-tools/schema-markup-generator/

Ho visto che il sito http://opendatasicilia.it/ è messo maluccio... se volete...

Sappiatemi dire

**Comment by gbvitrano** [comment]
Grazie per i suggerimenti, codice inserto :-)
