### ISSUE TITLE
Per forumPA

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#3]
@cirospat puoi contattarli e farti dare eventualmente logo e dicitura da inserire (penso media partner)

**Comment by cirospat** [comment]
Si certo lunedì lo faccio

**Comment by UO-TransizioneDigitaleComunePalermo** [comment]
già inviata email a Giovanna Stagno di ForumPA chiedendo logo e dicitura da inserire nel kit di comunicazione dell'evento
(Ciro)

**Comment by aborruso** [comment]
@cirospat non appena ti rispondono, con @gbvitrano inserite la nota sul media partner nel sito.

grazie

**Comment by cirospat** [comment]
si va bene

**Comment by cirospat** [comment]
oggi ho sentito Giovanna Stagno di ForumPA per argomento comunicazione dell'evento sul loro sito. Ho scritto qui: https://github.com/opendatasicilia/Palermo2018/issues/16#issuecomment-425404087

**Comment by cirospat** [comment]
**Da ForumPA**, Michela Stentella m.stentella@forumpa.it, che lavora a fianco di Giovanna Stagno g.stagno@forumpa.it, mi ha inviato un email in cui ci dice:

- Puoi mandarci un banner formato 300X100 (statico oppure animato), che pubblicheremo sul nostro sito forumpa.it con link all'evento

- Puoi mandarci una social card dell'evento che faremo girare sui nostri canali

- Inseriremo sul nostro sito e nella nostra NL un articolo di presentazione dell'evento (mandami tutti i materiali utili appena ce li hai) in cui vorrei inserire anche qualche virgolettato di commento (tuo, di  Gianni Dominici, e dimmi tu di chi altro ritieni sia utile e interessante)

- Inseriremo nella nostra NL la segnalazione dell'evento con link diretto alla pagina evento (ipotesi di uscite: NL del 24 ottobre, 31 ottobre, 7 novembre) 

Inoltre durante l'evento realizzeremo delle **videointerviste**.

**Comment by aborruso** [comment]
@cirospat ecco due delle cose:

- [banner formato 300X100](https://github.com/opendatasicilia/Palermo2018/raw/gh-pages/img/banner300x100.png);
- [social card 1024x512](https://github.com/opendatasicilia/Palermo2018/raw/gh-pages/img/socialcard1024x512.png).

Ho inserito anche [file modificabile](https://github.com/opendatasicilia/Palermo2018/raw/gh-pages/img/perForumPA.svg), nel caso servisse.

@gpirrotta @dtaibi ci pensate voi ad un articolo di presentazione? Penso sia da fare presto e userei pezzi di quanto già pubblicato.

Grazie a tutti

**Comment by cirospat** [comment]
mancano i loghi delle partnership su banner e social card

**Comment by aborruso** [comment]
@cirospat il banner mi pare piccolo per inserire loghi.

La social card con i loghi è qui

![socialcard1024x512fpa](https://user-images.githubusercontent.com/30607/46466774-741b4480-c7cc-11e8-9d50-4bb22bc4616d.png)

**Comment by aborruso** [comment]
@cirospat  c'era un errore, ecco quella nuova

![socialcard1024x512fpa](https://user-images.githubusercontent.com/30607/46467008-06234d00-c7cd-11e8-93dd-04ef42e5c23d.png)

**Comment by cirospat** [comment]
thanks,
ho condiviso il link con il team di ForumPA
