### ISSUE TITLE
Predisporre HTML per tasto donazione PayPal

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#4]

**Comment by peppelamensa** [comment]
Fatto ed inviato ad Andy

**Comment by aborruso** [comment]
Eccolo

```html
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="Y59U857L64E54">
<input type="image" src="https://www.paypalobjects.com/it_IT/IT/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal è il metodo rapido e sicuro per pagare e farsi pagare online.">
<img alt="" border="0" src="https://www.paypalobjects.com/it_IT/i/scr/pixel.gif" width="1" height="1">
</form>
```

**Comment by aborruso** [comment]
@peppelamensa riprenderei il testo fatto nel [2016](http://ods16.opendatasicilia.it/)

**Sostieni #ODS16 :-)** Vuoi aiutarci? Fai una donazione! L'associazione [Leva Digitale](http://levadigitale.it/) raccoglierà il budget e lo userà per le spese organizzative dell'evento. 

Se non hai l'account Paypal, puoi fare anche un bonifico a: Associazione Leva Digitale, Codice IBAN: **IT3XXXXXXXXXXX**. Ma per favore nella causale specifica qualcosa tipo Contributo per organizzazione #ODS16 o raduno 2016 opendatasicilia.

**Comment by aborruso** [comment]
@nelsonmau inizi a mettere il codice e questo testo in basso? E poi si modifica con le info che ci darà @peppelamensa

**Comment by nelsonmau** [comment]
@aborruso non avevo visto il testo e ho messo solo il form. Sistemi tu?

tnx
