### ISSUE TITLE
Creare testo "come arrivare"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#5]
Caro @marcofromsicily ,
questa è una cosa che tu sai preparare come pochi. Ti va di farlo?

Se accetti,  o in risposta qui da editare se vuoi nel tempo, o nel modo che preferisci.

Grazie

p.s. entro fine settembre, non c'è alcuna fretta

**Comment by marcofromsicily** [comment]
Accetto molto volentieri e senza fretta.

Aspettiamo l'apertura ufficiale del passante ferroviario.

**Comment by gbvitrano** [comment]
Sto preparando questa [mappa](http://u.osmfr.org/m/248933/) che potrebbe essere utile a chi viene da fuori Palermo, come orientarsi e spostarsi in città per partecipare al raduno
ho caricato le varie fermate della metropolitana, tram , le linee free di Amat del parcheggio basile e del centro storico, ci sono anche i principali parcheggi di intescambio e la ZTL

**Comment by marcofromsicily** [comment]
Ottimo lavoro, io aspetto ancora la comunicazione ufficiale di riapertura del passante prima di redigere il testo su come arrivare. 
Spero che il passante riapra entro il 01 ottobre.

**Comment by gbvitrano** [comment]
ok se ti può servire usa pure la mia mappa, se ci sono cose da aggiungere, dimmi pure :-)

**Comment by marcofromsicily** [comment]
Credo che la mappa al 90% va bene.
Dovremo fare un controllo, una volta riaperto il passante, su quali stazioni in direzione punta raisi sono realmente attive.

Toglierei dalla mappa i parcheggi oreto e lennon perchè non permettono di raggiungere facilmente palazzo dei normanni o i cantieri culturali.

Inserirei invece il parcheggio sotterraneo davanti al tribunale.

**Comment by gbvitrano** [comment]
Corretto. :-)

**Comment by marcofromsicily** [comment]
"Come arrivare".
------------------------------------
Venerdì 09 Novembre, 
Sede: [Palazzo Reale](http://www.federicosecondo.org/), [Piazza del Parlamento 1 Palermo](https://goo.gl/maps/SoJzUVXrK8R2) 

**Dall'[Aeroporto di Palermo](http://www.gesap.it/)**: prendete il [treno](http://www.trenitalia.com/) in direzione Palermo Centrale e scendete alla fermata " Palazzo Reale-Orleans", appena usciti dalla fermata vedrete il Palazzo Reale alla vostra destra.
Camminate intorno al palazzo lungo via del bastione, fino a giungere in Piazza del Parlamento.

**Dalla [Stazione Centrale di Palermo](https://www.palermocentrale.it/it/)**: prendete il [treno](http://www.trenitalia.com/) in direzione Punta Raisi e scendete alla fermata "Palazzo Reale-Orleans", appena usciti dalla fermata vedrete il Palazzo Reale alla vostra destra.
Camminate intorno al palazzo lungo via del bastione, fino a giungere in Piazza del Parlamento.

In alternativa, uscite dalla Stazione Centrale su Piazza Giulio Cesare, prendete la navetta gratuita [AMAT](http://amat.pa.it/) "ARANCIONE CENTRO STORICO" e scendete in Piazza Indipendenza.
Camminate intorno al palazzo lungo via del bastione, fino a giungere in Piazza del Parlamento.

**Dal Porto di Palermo**: Uscendo dal Porto vi troverete sulla via Francesco Crispi.
Attraversate la strada e prendete l'autobus [AMAT](http://amat.pa.it/) 107 in direzione Stazione Centrale.
Dalla Stazione Centrale proseguite con le indicazioni come sopra.

**Un giro nei dintorni**: Il [Palazzo Reale](http://www.federicosecondo.org/) è un [sito Unesco](http://arabonormannaunesco.it/) circondato da siti Unesco, a pochi passi si trovano la chiesa di [San Giovanni degli Eremiti](http://arabonormannaunesco.it/il-sito/monumenti/chiesa-di-san-giovanni-degli-eremiti/) e la [Cattedrale di Palermo](http://arabonormannaunesco.it/il-sito/monumenti/cattedrale-di-palermo/).

------------------------------------

Sabato 10 Novembre, 
Sede: [Crezi Plus](https://www.creziplus.it/), [Cantieri Culturali alla Zisa](https://www.facebook.com/Cantieri-Culturali-alla-Zisa-Eventi-1747804142114919/), [via Paolo Gili 4 Palermo](https://goo.gl/maps/96Ea7ACBPVK2)

**Dall'[Aeroporto di Palermo](http://www.gesap.it/)**: prendete il [treno](http://www.trenitalia.com/) in direzione Palermo Centrale e scendete alla fermata "Palermo Lolli".
Proseguite a piedi per via Dante, Piazza Principe di Camporeale, fino a giungere in via Paolo Gili 4.
Una volta entrati dentro i Cantieri Culturali alla Zisa, chiedete del Crezi Plus. 

**Dalla [Stazione Centrale di Palermo](https://www.palermocentrale.it/it/)**: prendete il [treno](http://www.trenitalia.com/) in direzione Punta Raisi e scendete alla fermata "Palermo Lolli".
Proseguite a piedi per via Dante, Piazza Principe di Camporeale, fino a giungere in via Paolo Gili 4.
Una volta entrati dentro i Cantieri Culturali alla Zisa, chiedete del Crezi Plus. 

**Dal Porto di Palermo**:  Uscendo dal porto imboccate la via Emerico Amari fino a giungere a Piazza Castelnuovo.
Posizionatevi nel lato della piazza che corrisponde alla via Dante e aspettate l'autobus [AMAT](http://amat.pa.it/) 106 in direzione "Parcheggio Emiri", scendendo alla fermata ["Piazza Principe di Camporeale"](https://goo.gl/maps/iQ46xGcD7H32).
Proseguite a piedi fino a giungere in via Paolo Gili 4.
Una volta entrati dentro i Cantieri Culturali alla Zisa, chiedete del Crezi Plus. 

**Un giro nei dintorni**: I Cantieri Culturali alla Zisa ospitano lo spazio "ZAC - Zisa Zona Arti Contemporanee" ed il ["Centro Internazionale di fotografia"](https://www.facebook.com/Centro-Internazionale-di-fotografia-1507200175959704/), entrambi meritano una visita.

A pochi passi dai Cantieri Culturali si trovano il giardino ed il [Castello della Zisa](https://www.coopculture.it/heritage.cfm?id=222), patrimonio Unesco. 


------------------------------------

Informazioni utili sulla città:

* La [mappa ufficiale dell'evento è disponibile qui](http://umap.openstreetmap.fr/it/map/ods18-linked-opendata-sicilia_248933#13/38.1155/13.3626).

* Per informazioni sui mezzi pubblici scaricate l'app di [Moovit](https://moovit.com/) oppure gli [Open Data Comunali](https://opendata.comune.palermo.it/opendata-archivio-dataset.php).  :)

* Palermo è [Capitale Italiana della Cultura 2018](https://www.palermocapitalecultura.it/).

* Una lista di tutti gli alloggi dove dormire è disponibile sul [Portale del Turismo](https://turismo.comune.palermo.it/turismo.php), il [Comune ha sottoscritto un accordo con Airbnb per la riscossione dell'imposta di soggiorno](https://www.comune.palermo.it/noticext.php?id=17283).

* Una [mappa](http://arabonormannaunesco.it/downloads/unesco-arabonormanna-mappa-ita.pdf) ed un [opuscolo informativo](http://arabonormannaunesco.it/downloads/unesco-arabonormanna-opuscolo-informativo-ITA.pdf) su Palermo sono disponibili per il download sul [Portale Unesco](http://arabonormannaunesco.it/risorse/).

* La spiaggia di [Mondello](https://youtu.be/4vM7-Wl_w7I) è raggiungibile dal centro città prendendo l'Autobus [AMAT](http://amat.pa.it/) 806 da [Piazza Ruggero Settimo](https://goo.gl/maps/uxhtj9md5L92).

* Non toccate le banane.

**Comment by gbvitrano** [comment]
Blocco inserito nel sito  :-)

**Comment by marcofromsicily** [comment]
è saltato il link alla tua mappa?

**Comment by aborruso** [comment]
@gbvitrano ci metti un ancora (come in http://ods2018.opendatasicilia.it/#proponi) e poi chiudi la issue?

Grazie

**Comment by marcofromsicily** [comment]
Direi di non chiudere la Issue perchè potrebbero esserci aggiornamenti da segnalare prima di Novembre.

**Comment by cirospat** [comment]
la mappa di Gianni http://umap.openstreetmap.fr/it/map/ods18-linked-opendata-sicilia_248933#14/38.1155/13.3626
dove è nella pagina di presentazione di ODS18 ?

**Comment by gbvitrano** [comment]
@aborruso le ancore già sono inserite [#arrivare](http://ods2018.opendatasicilia.it/#arrivare) 
 http://ods2018.opendatasicilia.it/#arrivare

[#informazioni](http://ods2018.opendatasicilia.it/#info#informazioni) 
 http://ods2018.opendatasicilia.it/#info#informazioni

**Comment by gbvitrano** [comment]
@cirospat la mappa ancora non è stata caricata, non è completa, appena posso inerisco anche i luoghi indicati da @marcofromsicily e dopo la posso mettere in iframe sotto le  **Informazioni utili sulla città** oppure inerisco un'immagine cliccabile che punta alla mappa

**Comment by gbvitrano** [comment]
@marcoalfano per chi viene in auto da fuori Palermo, non lo indichiamo il parcheggio Basile e la navetta free per il 9 novembre?

**Comment by marcofromsicily** [comment]
Si per il 09 Novembre il Parcheggio Basile dovrebbe essere la migliore opzione.

Dopo il paragrafo "Dal Porto di Palermo" possiamo aggiungere......

**In auto**: Parcheggiate in via Ernesto Basile nei pressi del [Capolinea AMAT](https://goo.gl/maps/yhAYydCDAgH2), in modo da poter prendere la navetta gratuita "Express" dell'AMAT fino a Pizza Indipendenza.
Camminate poi intorno al palazzo lungo via del bastione, fino a giungere in Piazza del Parlamento.

----------------------------------------------------------------

Per il 10 Novembre, il parcheggio più vicino è Emiri, ma credo che solo il 106 passi da li.

Conviene suggerire il parcheggio del tribunale, che anche se è raggiungibile solo a piedi gli permette di lasciare la macchina in una zona centrale, buona anche per vedere la città?

**Comment by gbvitrano** [comment]
@marcoalfano per accedere al parcheggio di del tribunale si entra dentro la ZTL?  dovremmo anche dire del pass giornaliero.

**Comment by gbvitrano** [comment]
Aggiunto il testo per l'evento del 9 novembre e inserito iframe della mappa (ancora da aggiornare con le info di Marco)

**Comment by gbvitrano** [comment]
> è saltato il link alla tua mappa?

non l'avevo visto, :-)

**Comment by cirospat** [comment]
credo che si dovrebbe inserire nel testo "Come arrivare" anche i numeri dei bus che transitano [da Piazza Principe di Camporeale provenienti dal centro (ad es. dal Politeama)](https://moovit.com/?from=Teatro%20Politeama&to=Piazza%20Principe%20Di%20Camporeale,%20Palermo&fll=38.12528_13.35616&tll=38.11954_13.3407&utm_source=widget&o=1&metroId=2804&lang=it): numeri 106,124,134. Questo perchè molti già saranno a Palermo dal giorno prima (il 9 nov) e quindi per raggiungere i Cantieri della Zisa usano i bus (da li non passa tram).

Stessa cosa per il 9 nov.: molti saranno già a Palermo da giorno prima (l'8 nov) e quindi hanno necessità di sapere quali bus/tram transitano da Piazza indipendenza provenienti dal centro (teatro Massimo, Politeama, zona Stazione Centrale ferroviaria).

Cioè **non mettere solo come arrivare da aeroporto/porto/stazione ferroviaria, ma anche come arrivare coi bus/tram se uno già si trova nel centro urbano**.

**Comment by gbvitrano** [comment]
@cirospat per me va bene, attendo le modifiche se @marcofromsicily è d'accordo.
io ho inserito la mappa in iframe nella visualizzazione dektop o tablet con risoluzione superiore a 850 px
immagine cliccabile a risoluzioni inferiori. (devo sempre aggiornarla )

**Comment by marcofromsicily** [comment]
@gbvitrano il parcheggio del tribunale si trova nel perimetro della ZTL, ed il perimetro è percorribile senza pagare il pass.
Il difetto del parcheggio è che si trova ad 1km a piedi dai cantieri culturali, ma è coperto, custodito ed in pieno centro.

@cirospat ok possiamo aggiungere le indicazioni per entrambi gli eventi, partendo da Piazza Castelnuovo.
Non inserirei ulteriori indicazioni per non appesantire il testo e perchè soluzioni personalizzate possono essere ricercate con Moovit.

--------------------------------------

Venerdì 09 Novembre

**Da Piazza Castelnuovo, centro città**: Posizionatevi nella [fermata al centro della piazza](https://goo.gl/maps/hoecV4mtxk22) e prendete l'autobus AMAT 104 in direzione "Parcheggio Basile".
Scendete in Piazza Indipendenza, camminate intorno al Palazzo Reale lungo via Vittorio Emanuele, fino a giungere in Piazza del Parlamento.

Sabato 10 Novembre

**Da Piazza Castelnuovo, centro città**: Posizionatevi nel [lato della piazza che corrisponde alla via Dante](https://goo.gl/maps/tTyNYngYVQ22) e aspettate l'autobus AMAT 106 in direzione "Parcheggio Emiri", scendendo alla fermata "Piazza Principe di Camporeale".
Proseguite a piedi fino a giungere in via Paolo Gili 4.
Una volta entrati dentro i Cantieri Culturali alla Zisa, chiedete del Crezi Plus.

**Comment by gbvitrano** [comment]
Nuovo testo inserito :-)

**Comment by cirospat** [comment]
thanks

_
*Ciro *





Il giorno mar 25 set 2018 alle ore 14:08 Giovan Battista Vitrano <
notifications@github.com> ha scritto:

**Comment by cirospat** [comment]
@gbvitrano tempo fa fece questa mappa dagli open data di AirBnB
http://u.osmfr.org/m/198624/

che ne dite di metterla sulla pagina di benvenuto del raduno nella sezione **Informazioni utili sulla città** 

potrebbe aiutare, no? e fa vedere anche come noi riusiamo i dati aperti ;)

**Comment by marcofromsicily** [comment]
Ok, suggerisco di rimodulare il punto come segue.

-------------------------------------------------------------------------

Una lista di alloggi dove dormire è disponibile sul [Portale del Turismo](https://turismo.comune.palermo.it/) e nella mappa [Palermo Airbnb](http://umap.openstreetmap.fr/it/map/palermo-airbnb-opendata-gennaio-2018-test-_198624#12/38.1397/13.4073) creata con gli open data.
Vi segnaliamo che a Palermo è in vigore l'[imposta di soggiorno](https://www.comune.palermo.it/noticext.php?id=16822) e che viene [riscossa anche da Airbnb tramite un accordo col comune](https://www.comune.palermo.it/noticext.php?id=17283).

**Comment by gbvitrano** [comment]
Scusate il ritardo... :-)
ho inserito il nuovo blocco **Alloggi** sotto il blocco della mappa ufficiale, 
ho inserito il testo e un'immagine della mappa Airbnb con il link

**Comment by cirospat** [comment]
oppobello
thanks







Il giorno ven 28 set 2018 alle ore 10:46 Giovan Battista Vitrano <
notifications@github.com> ha scritto:

**Comment by marcofromsicily** [comment]
**Riattivato servizio per Punta Raisi** 

Sarà riattivato il 7/10 il collegamento ferroviario tra la stazione di Palermo Centrale e l’aeroporto “Falcone e Borsellino”.

Domenica il primo treno partirà alle 6.05 da Palermo Centrale, mentre l’ultima partenza da Punta Raisi è prevista alle 21.52. 

L’offerta commerciale di Trenitalia per l’aeroporto prevede nei giorni feriali 61 treni al giorno, con una cadenza di due treni/ora.

Disponibili dal 7/10 anche le due nuove fermate di La Malfa e Sferracavallo.

http://www.trenitalia.com/tcom/Treni-Regionali/Sicilia/Servizi-Punta-Raisi
