### ISSUE TITLE
Associare nome di dominio a repo

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#6]
@gpirrotta propone ods2018.opendatasicilia.it

Se non arrivano altre proposte, domani lo attiviamo

**Comment by gbvitrano** [comment]
Visto il nome dell'evento  Linked OpenData Sicilia

linked2018.opendatasicilia.it

linkedods2018.opendatasicilia.it

odslinked2018.opendatasicilia.it

**Comment by UO-TransizioneDigitaleComunePalermo** [comment]
raduno2018.opendatasicilia.it
che ne dite?
(Ciro con account GitHub ufficio)

**Comment by gpirrotta** [comment]
I siti web delle conference scientifiche (ma non solo) solitamente usano come dominio il pattern
(siglaconfenza+anno).dominio.estensione.
La mia proposta, cioè ods2018.opendatasicilia.it va in questa direzione, cioè quella di dare al raduno una riconoscibilità negli anni, creando una serialità sul Web che possa essere facilmente identificabile nel tempo.
Cioè, vorrei evitare di avere
ods2016.opendatasicilia.it
2017.opendatasicilia.it
linked2018.opendatasicilia.it

Questa riconoscibilità è anche utile nel mondo social. Solitamente gli hashtag di riferimento per le conferenze sono proprio queste sigle, nel nostro caso potrebbe essere #ods2018.

my2c

**Comment by cirospat** [comment]
Giovanni voleva solo dire:
ODS nei secoli dei secoli
:-)



_
*Ciro Spataro*
cirospat@gmail.com
cirospat.readthedocs.io




Il giorno 12 settembre 2018 07:02, Giovanni Pirrotta <
notifications@github.com> ha scritto:

**Comment by picomiles** [comment]
gpirrotta non poteva dirlo meglio di così

+1


Il mer 12 set 2018, 09:29 ciro spataro <notifications@github.com> ha
scritto:

**Comment by giuragu** [comment]
Mi piace l’idea temporale di Giovanni

**Comment by aborruso** [comment]
Modifiche DNS fatte. Tra qualche ora dovremmo avere URL funzionante
