### ISSUE TITLE
Creare branch gh-pages

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#7]
In modo da poter avere un master per fare un po' tutto e un altro contenitore soltanto per l'HTML del sito

**Comment by nelsonmau** [comment]
@aborruso fatto, ma non ho capito come lo vuoi organizzare, quindi palla a te

**Comment by aborruso** [comment]
Voglio usare il branch gh-pages come source del repo, da tenere "staccato" dal resto del repo in cui metteremo anche altro di non legato al sito.
Quindi il repo master come contenitore generico e gh-pages (che setterò come [orfano](https://git-scm.com/docs/git-checkout/1.7.3.1#git-checkout---orphan)) come source del repo.

Faccio una piccola modifica rispetto a quello che hai fatto e poi avviso e chiudo issue.

Grazie

**Comment by aborruso** [comment]
Ecco le note che ho messo anche nel README

# Struttura repo

## branch gh-pages

È il branch che fa da **source** al **sito web** e non è in relazione con il master.

Chi lavora sul sito quindi farà modifiche, o _pull request_ o nuovi brach di sviluppo a partire da `gh-pages`-

## brach master

È un branch che si può usare come contenitore generico per **"altro" dal sito**.
