### ISSUE TITLE
Creare form iscrizione eventbrite per iscriversi a evento

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Palermo2018#8]
@picomiles te ne vuoi/puoi occupare tu??

**Comment by aborruso** [comment]
Lo assegno a me

**Comment by picomiles** [comment]
scusami @aborruso mi sto accorgendo solo ora che mi avevi citato.
Oggi non riesco, ma posso provarci, diciamo, da domani

**Comment by aborruso** [comment]
@picomiles ti mando credenziali.

Gli eventi sono già creati, da qui in poi ti chiediamo la cortesia di fare eventuali modifiche e gestire i task correlati.
